/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as StyleGuideRouteImport } from './routes/style-guide'
import { Route as DocsRouteImport } from './routes/docs'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ApiListIndexRouteImport } from './routes/api-list/index'
import { Route as ApiListIdRouteImport } from './routes/api-list/$id'

const StyleGuideRoute = StyleGuideRouteImport.update({
  id: '/style-guide',
  path: '/style-guide',
  getParentRoute: () => rootRouteImport,
} as any)
const DocsRoute = DocsRouteImport.update({
  id: '/docs',
  path: '/docs',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiListIndexRoute = ApiListIndexRouteImport.update({
  id: '/api-list/',
  path: '/api-list/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiListIdRoute = ApiListIdRouteImport.update({
  id: '/api-list/$id',
  path: '/api-list/$id',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/docs': typeof DocsRoute
  '/style-guide': typeof StyleGuideRoute
  '/api-list/$id': typeof ApiListIdRoute
  '/api-list/': typeof ApiListIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/docs': typeof DocsRoute
  '/style-guide': typeof StyleGuideRoute
  '/api-list/$id': typeof ApiListIdRoute
  '/api-list': typeof ApiListIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/docs': typeof DocsRoute
  '/style-guide': typeof StyleGuideRoute
  '/api-list/$id': typeof ApiListIdRoute
  '/api-list/': typeof ApiListIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    '/' | '/about' | '/docs' | '/style-guide' | '/api-list/$id' | '/api-list/'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/about' | '/docs' | '/style-guide' | '/api-list/$id' | '/api-list'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/docs'
    | '/style-guide'
    | '/api-list/$id'
    | '/api-list/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  DocsRoute: typeof DocsRoute
  StyleGuideRoute: typeof StyleGuideRoute
  ApiListIdRoute: typeof ApiListIdRoute
  ApiListIndexRoute: typeof ApiListIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/style-guide': {
      id: '/style-guide'
      path: '/style-guide'
      fullPath: '/style-guide'
      preLoaderRoute: typeof StyleGuideRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/docs': {
      id: '/docs'
      path: '/docs'
      fullPath: '/docs'
      preLoaderRoute: typeof DocsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api-list/': {
      id: '/api-list/'
      path: '/api-list'
      fullPath: '/api-list/'
      preLoaderRoute: typeof ApiListIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api-list/$id': {
      id: '/api-list/$id'
      path: '/api-list/$id'
      fullPath: '/api-list/$id'
      preLoaderRoute: typeof ApiListIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  DocsRoute: DocsRoute,
  StyleGuideRoute: StyleGuideRoute,
  ApiListIdRoute: ApiListIdRoute,
  ApiListIndexRoute: ApiListIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
