// var table = document.querySelectorAll('.wikitable');
// var tableRows = [...table[1].querySelectorAll('tr')];
// var data = tableRows.map(row => row.innerText);
// copy(data);

var season1 = [
    ["1a", "1a", "The Big Problem!", "Butch Hartman and Jaime Diaz", "Steve Marmel", "Butch Hartman and Bernie Petterson", "March 30, 2001"],
    ["1b", "1b", "Power Mad!", "Butch Hartman", "Written by: Steve Marmel Story by: Mike Bell and Steve Marmel (story)", "Butch Hartman", "March 30, 2001"],
    ["2a", "2a", "Spaced Out", "Butch Hartman", "Mike Bell, Butch Hartman & Steve Marmel", "Butch Hartman and Barry Bunce", "April 6, 2001"],
    ["2b", "2b", "TransParents!", "Butch Hartman and Larry Leichliter", "Butch Hartman and Steve Marmel", "Butch Hartman and Joe Daniello", "April 6, 2001"],
    ["3a", "3a", "A Wish Too Far!", "Butch Hartman", "Steve Marmel", "Butch Hartman and Erik Wiese", "April 13, 2001"],
    ["3b", "3b", "Tiny Timmy!", "Butch Hartman and Larry Leichliter", "Steve Marmel Story by: Butch Hartman, Mike Bell, and Steve Marmel (story)", "Paul McEvoy", "April 13, 2001"],
    ["4a", "4a", "Father Time!", "Butch Hartman and Jaime Diaz", "Butch Hartman and Steve Marmel", "John Fountain and Butch Hartman", "April 20, 2001"],
    ["4b", "4b", "Apartnership!", "Butch Hartman", "Butch Hartman and Steve Marmel", "John Fountain and Butch Hartman", "April 20, 2001"],
    ["5a", "5a", "Chin Up!", "Butch Hartman", "Steve Marmel", "Paul McEvoy and Butch Hartman", "April 27, 2001"],
    ["5b", "5b", "Dog's Day Afternoon", "Butch Hartman and Larry Leichliter", "Steve Marmel", "Paul McEvoy and Butch Hartman", "April 27, 2001"],
    ["6a", "6a", "Dream Goat!", "Butch Hartman and Larry Leichliter", "Butch Hartman Story by: Butch Hartman, Mike Bell, and Steve Marmel (story)", "John Fountain", "May 4, 2001"],
    ["6b", "6b", "The Same Game", "Butch Hartman", "Butch Hartman and Steve Marmel", "Paul McEvoy and Butch Hartman", "May 4, 2001"],
    ["7", "7", "Christmas Everyday!", "Butch Hartman", "Butch Hartman and Steve Marmel Story by: Butch Hartman, Tracy Berna, and Steve Marmel (story)", "Butch Hartman and Bob Boyle", "December 12, 2001"]
];

var season2 = [
    ["8a", "1a", "Boys in the Band", "Butch Hartman", "Butch Hartman & Steve Marmel", "Butch Hartman and Paul McEvoy", "March 1, 2002"],
    ["8b", "1b", "Hex Games", "Butch Hartman", "Tim O'Rourke", "Bob Boyle", "March 1, 2002"],
    ["9a", "2a", "Boy Toy", "Butch Hartman", "Butch Hartman & Steve Marmel", "Butch Hartman and Jim Schumann", "March 8, 2002"],
    ["9b", "2b", "Inspection Detection", "Butch Hartman", "Spencer Green Story by: Butch Hartman & Steve Marmel (story)", "Butch Hartman", "March 8, 2002"],
    ["10a", "3a", "Action Packed", "John Fountain and Butch Hartman", "Tracy Berna and Steve Marmel", "John Fountain", "March 22, 2002"],
    ["10b", "3b", "Smarty Pants", "John Fountain and Butch Hartman", "Tracy Berna", "John Fountain", "March 22, 2002"],
    ["11a", "4a", "Timvisible", "Butch Hartman", "Butch Hartman and Steve Marmel", "Butch Hartman and Paul McEvoy", "April 26, 2002"],
    ["11b", "4b", "That Old Black Magic", "Sarah Frost and Butch Hartman", "Butch Hartman and Steve Marmel", "Jim Schumann, Butch Hartman, and Sarah Frost", "April 26, 2002"],
    ["12a", "5a", "Super Bike", "Butch Hartman", "Jack Thomas", "Butch Hartman", "May 10, 2002"],
    ["12b", "5b", "A Mile in My Shoes", "Gary Conrad and Butch Hartman", "Tim O'Rourke, Butch Hartman, and Steve Marmel", "Chris Robertson", "May 10, 2002"],
    ["13a", "6a", "Foul Balled", "John Fountain and Butch Hartman", "Butch Hartman and Steve Marmel", "Chris Robertson and John Fountain", "June 7, 2002"],
    ["13b", "6b", "The Boy Who Would Be Queen", "Sarah Frost and Butch Hartman", "Steve Marmel and Butch Hartman", "Butch Hartman and Sarah Frost", "June 7, 2002"],
    ["14a", "7a", "Totally Spaced Out", "John Fountain and Butch Hartman", "Steve Marmel and Jack Thomas", "John Fountain and Paul McEvoy", "July 12, 2002"],
    ["14b", "7b", "The Switch Glitch", "Gary Conrad and Butch Hartman", "Story by: Jenny Nissenson (story) Butch Hartman, Steve Marmel, and Jenny Nissenson", "Jim Schumann, Gary Conrad, and Butch Hartman", "July 12, 2002"],
    ["15a", "8a", "Mighty Mom & Dyno Dad", "John Fountain and Butch Hartman", "Butch Hartman and Steve Marmel", "John Fountain and Chris Robertson", "September 6, 2002"],
    ["15b", "8b", "Knighty Knight", "Sarah Frost and Butch Hartman", "Butch Hartman, Steve Marmel, and Jack Thomas", "Butch Hartman, Sarah Frost, and Heather Martinez", "September 6, 2002"],
    ["16a", "9a", "Fairy Fairy Quite Contrary", "John Fountain and Butch Hartman", "Jack Thomas, Butch Hartman, and Steve Marmel", "John Fountain and Jim Schumann", "September 13, 2002"],
    ["16b", "9b", "Nectar of the Odds", "Sarah Frost and Butch Hartman", "Jack Thomas", "Sarah Frost and Butch Hartman", "September 13, 2002"],
    ["17a", "10a", "Hail to the Chief", "Gary Conrad and Butch Hartman", "Steven Banks, Jack Thomas, and Steve Marmel", "Gary Conrad and Butch Hartman", "September 27, 2002"],
    ["17b", "10b", "Twistory", "Gary Conrad and Butch Hartman", "Butch Hartman, Steve Marmel, and Jack Thomas", "Paul McEvoy and Butch Hartman", "September 27, 2002"],
    ["18a", "11a", "Fool's Day Out", "Gary Conrad and Butch Hartman", "Jack Thomas, Butch Hartman & Steve Marmel", "Chris Robertson and Gary Conrad", "October 11, 2002"],
    ["18b", "11b", "Deja Vu", "Butch Hartman", "Jack Thomas, Butch Hartman & Steve Marmel", "Butch Hartman", "October 11, 2002"],
    ["19", "12", "Scary Godparents", "John Fountain, Gary Conrad, and Butch Hartman", "Butch Hartman, Steve Marmel, and Jack Thomas", "Heather Martinez, Chris Robertson, Shawn Murray, Butch Hartman, and John Fountain", "October 29, 2002"],
    ["20a", "13a", "Ruled Out", "Gary Conrad", "Karin Gutman", "Butch Hartman and Jim Schumann", "November 8, 2002"],
    ["20b", "13b", "That's Life!", "Sarah Frost and Butch Hartman", "Spencer Green, Butch Hartman, and Steve Marmel", "Butch Hartman and Jim Schumann", "November 8, 2002"],
    ["21a", "14a", "Shiny Teeth", "Butch Hartman", "Butch Hartman and Steve Marmel", "Heather Martinez and Butch Hartman", "November 30, 2002"],
    ["21b", "14b", "Odd, Odd West", "John Fountain and Butch Hartman", "Steve Marmel and Jack Thomas", "Jim Schumann and John Fountain", "November 30, 2002"],
    ["22a", "15a", "Cosmo Con", "Wincat Alcala and Butch Hartman", "Scott Fellows and Jack Thomas", "Wincat Alcala", "January 10, 2003"],
    ["22b", "15b", "Wanda's Day Off!", "Sarah Frost and Butch Hartman", "Jack Thomas", "Heather Martinez and Shawn Murray", "January 10, 2003"]
];

var season3 = [
    ["23", "1", "Information Stupor Highway", "Sarah Frost, John Fountain, and Butch Hartman", "Butch Hartman and Steve Marmel", "Butch Hartman, Jim Schumann, Chris Robertson, and John Fountain", "January 20, 2003"],
    ["24a", "2a", "Odd Jobs", "Gary Conrad", "Scott Fellows", "Dave Thomas and Chris Robertson", "January 27, 2003"],
    ["24b", "2b", "Movie Magic", "Wincat Alcala and Butch Hartman", "Scott Fellows and Jack Thomas", "Ian Graham", "January 27, 2003"],
    ["25", "3", "Love Struck!", "Sarah Frost, Gary Conrad, and Butch Hartman", "Scott Fellows, Steve Marmel, and Butch Hartman", "Dave Thomas, Chris Robertson, Heather Martinez, Shawn Murray and Butch Hartman", "February 14, 2003"],
    ["26a", "4a", "Most Wanted Wish", "Gary Conrad", "Scott Fellows", "Dave Thomas", "May 2, 2003"],
    ["26b", "4b", "This is Your Wish", "Sarah Frost", "Butch Hartman, Steve Marmel, Scott Fellows, and Jack Thomas", "Heather Martinez and Shawn Murray", "May 2, 2003"],
    ["27a", "5a", "The Crimson Chin Meets Mighty Mom & Dyno Dad!", "Ken Bruce and Butch Hartman", "Butch Hartman and Steve Marmel", "Heather Martinez and Shawn Murray", "May 9, 2003"],
    ["27b", "5b", "Engine Blocked", "Wincat Alcala and Butch Hartman", "Jack Thomas", "Ian Graham and Butch Hartman", "May 9, 2003"],
    ["28a", "6a", "Sleepover and Over", "Ken Bruce and Butch Hartman", "Scott Fellows, Steve Marmel, and Jack Thomas", "Heather Martinez and Shawn Murray", "May 17, 2003"],
    ["28b", "6b", "Mother Nature", "Gary Conrad", "Scott Fellows and Jack Thomas", "Dave Thomas and Chris Robertson", "May 17, 2003"],
    ["29a", "7a", "Beddy Bye", "Wincat Alcala and Butch Hartman", "Story by: Mike Lewis (story) Steve Marmel, Jack Thomas, and Scott Fellows", "Erik Wiese", "May 23, 2003"],
    ["29b", "7b", "The Grass is Greener", "Ken Bruce and Butch Hartman", "Steve Marmel, Jack Thomas, and Spencer Green", "Ian Graham and Butch Hartman", "May 23, 2003"],
    ["30", "8", "The Secret Origin of Denzel Crocker!", "Gary Conrad, Sarah Frost, and Wincat Alcala", "Butch Hartman and Steve Marmel", "Dave Thomas, Ian Graham, Heather Martinez, and Shawn Murray", "June 27, 2003"],
    ["31", "9", "Abra-Catastrophe!", "Butch Hartman", "Butch Hartman and Steve Marmel", "John Fountain, Ian Graham, Heather Martinez, Shawn Murray, Chris Robertson, Dave Thomas, and Butch Hartman", "July 12, 2003"],
    ["32a", "10a", "MicroPhony", "Gary Conrad", "Butch Hartman, Steve Marmel and Jack Thomas", "Dave Thomas", "August 1, 2003"],
    ["32b", "10b", "So Totally Spaced Out", "Sarah Frost and Butch Hartman", "Steve Marmel and Jack Thomas", "Chris Robertson", "August 1, 2003"],
    ["33a", "11a", "Pipe Down!", "Sarah Frost", "Butch Hartman, Steve Marmel, Jack Thomas, and Scott Fellows", "Dave Thomas", "September 26, 2003"],
    ["33b", "11b", "The Big Scoop!", "Wincat Alcala and Gary Conrad", "Butch Hartman and Steve Marmel", "Ian Graham and Lane Lueras", "September 26, 2003"],
    ["34a", "12a", "Crime Wave", "Wincat Alcala and Butch Hartman", "Butch Hartman and Steve Marmel", "Heather Martinez and Shawn Murray", "October 10, 2003"],
    ["34b", "12b", "Odd Ball", "Sarah Frost", "Jack Thomas, Scott Fellows, and Jim Hecht", "Ian Graham", "October 10, 2003"],
    ["35a", "13a", "Where's Wanda?", "Gary Conrad", "Jack Thomas", "Heather Martinez and Shawn Murray", "October 18, 2003"],
    ["35b", "13b", "Imaginary Gary", "Gary Conrad", "Steve Marmel and Butch Hartman", "Heather Martinez and Shawn Murray", "October 18, 2003"],
    ["36a", "14a", "Miss Dimmsdale", "Sarah Frost", "Scott Fellows", "Dave Thomas and Ian Graham", "November 7, 2003"],
    ["36b", "14b", "Mind Over Magic", "Gary Conrad", "Jack Thomas", "Heather Martinez and Shawn Murray", "November 7, 2003"],
    ["37a", "15a", "Kung Timmy", "Wincat Alcala and Gary Conrad", "Jack Thomas and Scott Fellows", "Heather Martinez and Shawn Murray", "November 11, 2003"],
    ["37b", "15b", "Which Witch is Which?", "Sarah Frost and Ken Bruce", "Butch Hartman and Jack Thomas", "Butch Hartman", "November 11, 2003"],
    ["38a", "16a", "Hard Copy", "Sarah Frost", "Scott Fellows", "Heather Martinez and Shawn Murray", "November 14, 2003"],
    ["38b", "16b", "Parent Hoods", "Gary Conrad and Ken Bruce", "Butch Hartman, Steve Marmel, and Jack Thomas", "Maureen Mascarina and Dave Thomas", "November 14, 2003"],
    ["39a", "17a", "Chip Off the Old Chip", "Wincat Alcala and Butch Hartman", "Butch Hartman, Steve Marmel, and Jack Thomas", "Dave Thomas and Butch Hartman", "November 21, 2003"],
    ["39b", "17b", "Snow Bound", "Sarah Frost", "Scott Fellows", "Ian Graham and Ray Angrum", "November 21, 2003"]
];

var season4 = [
    ["40", "1", "The Big Superhero Wish!", "Gary Conrad and Sarah Frost", "Butch Hartman and Steve Marmel", "Heather Martinez, Shawn Murray, Aaron Rozenfeld, and Tom King", "February 16, 2004"],
    ["41a", "2a", "Vicky Loses Her Icky", "Sarah Frost", "Andrew Nicholls and Darrell Vickers", "Shawn Murray and Heather Martinez", "February 20, 2004"],
    ["41b", "2b", "Pixies Inc.", "Gary Conrad", "Jack Thomas", "Maureen Mascarina, Aaron Rozenfeld, and Wincat Alcala", "February 20, 2004"],
    ["42a", "3a", "Baby Face", "Ken Bruce", "Scott Fellows", "Maureen Mascarina, Chris Garbutt, and Dave Needham", "March 19, 2004"],
    ["42b", "3b", "Mr. Right!", "Gary Conrad", "Jack Thomas", "Ian Graham and Aaron Rozenfeld", "March 19, 2004"],
    ["43", "4", "The Jimmy Timmy Power Hour", "Keith Alcorn and Butch Hartman", "Gene Grillo, Butch Hartman, and Steve Marmel Rico Hall (story)", "Paul Claerhout, Jason Dorf, Rod Douglas, Dan Nosella, Ian Graham, Maureen Mascarina, Heather Martinez & Shawn Murray", "May 7, 2004"],
    ["44a", "5a", "Power Pals", "Sarah Frost", "Scott Fellows", "Mike Manley", "May 18, 2004"],
    ["44b", "5b", "Emotion Commotion!", "Ken Bruce", "Jack Thomas", "Ian Graham and Maureen Mascarina", "May 18, 2004"],
    ["45a", "6a", "Lights...Camera...Adam!", "Sarah Frost and Gary Conrad", "Jack Thomas, Scott Fellows, Steve Marmel, and Butch Hartman", "Mike Manley", "June 1, 2004"],
    ["45b", "6b", "A Bad Case of Diary-Uh!", "Sarah Frost and Gary Conrad", "Karin Gutman", "Heather Martinez and Shawn Murray", "June 1, 2004"],
    ["46a", "7a", "The Odd Couple", "Gary Conrad", "Cynthia True", "Heather Martinez and Shawn Murray", "June 14, 2004"],
    ["46b", "7b", "Class Clown", "Ken Bruce", "Andrew Nicholls and Darrell Vickers", "Ian Graham and Tom King", "June 14, 2004"],
    ["47a", "8a", "Who's Your Daddy?", "Gary Conrad", "Andrew Nicholls and Darrell Vickers Bob Boyle and Lewis Foulke (story)", "Maureen Mascarina and Aaron Rozenfeld", "June 18, 2004"],
    ["47b", "8b", "Homewrecker", "Ken Bruce", "Cynthia True", "Tom King and Shawn Murray", "June 18, 2004"],
    ["48", "9", "Crash Nebula", "Butch Hartman", "Butch Hartman and Steve Marmel", "Erik Wiese", "July 2, 2004"],
    ["49", "10", "Channel Chasers", "Butch Hartman", "Steve Marmel and Butch Hartman", "Dave Thomas, Ray Angrum, Chris Graham, Butch Hartman, Tom King, Mike Manley, Heather Martinez, Maureen Mascarina, Shawn Murray, Aaron Rozenfeld & Erik Wiese", "July 23, 2004"],
    ["50", "11", "Shelf Life", "Wincat Alcala and Butch Hartman", "Butch Hartman, Steve Marmel, and Jack Thomas", "Wincat Alcala, Ian Graham, and Butch Hartman", "September 10, 2004"],
    ["51a", "12a", "A New Squid in Town!", "Ken Bruce", "Steve Marmel and Butch Hartman", "Tom King and Butch Hartman", "November 27, 2004"],
    ["51b", "12b", "Wish Fixers", "Sarah Frost", "Scott Fellows", "Maureen Mascarina and Aaron Rozenfeld", "November 27, 2004"],
    ["52a", "13a", "Fairy Friends & Neighbors!", "Sarah Frost", "Dave Thomas (story) Scott Fellows and Jack Thomas", "Heather Martinez, Shawn Murray, and Dave Thomas", "November 27, 2004"],
    ["52b", "13b", "Just the Two of Us!", "Ken Bruce", "Jack Thomas, Scott Fellows, and Jim Hecht", "Maureen Mascarina and Aaron Rozenfeld", "November 27, 2004"],
    ["53a", "14a", "Catman Meets the Crimson Chin", "Ken Bruce", "Scott Fellows", "Shawn Murray and Tom King", "January 17, 2005"],
    ["53b", "14b", "Genie Meanie Minie Mo", "Gary Conrad", "Jack Thomas", "Maureen Mascarina and Aaron Rozenfeld", "January 17, 2005"]
];

var season5 = [
    ["54a", "1a", "Nega-Timmy", "Gary Conrad", "Story by: Dave Thomas (story) Scott Fellows & Jack Thomas", "Dave Thomas and Butch Hartman", "February 14, 2005"],
    ["54b", "1b", "Love at First Height", "Ken Bruce", "Joel Zimmer", "Maureen Mascarina", "February 14, 2005"],
    ["55a", "2a", "Truth or Cosmoquences", "Gary Conrad", "Jack Thomas", "Heather Martinez and Shawn Murray", "February 15, 2005"],
    ["55b", "2b", "Beach Bummed!", "Sarah Frost", "Scott Fellows and Jack Thomas", "Dave Thomas, Tom King, and Heather Martinez", "February 15, 2005"],
    ["56a", "3a", "You Doo!", "Gary Conrad", "Scott Fellows and Jack Thomas", "Heather Martinez", "February 16, 2005"],
    ["56b", "3b", "Just Desserts!", "Sarah Frost", "Scott Fellows", "Tom King", "February 16, 2005"],
    ["57a", "4a", "Back to the Norm", "Gary Conrad", "Jack Thomas", "Dave Thomas", "February 17, 2005"],
    ["57b", "4b", "Teeth for Two", "Ken Bruce", "Cynthia True", "Maureen Mascarina", "February 17, 2005"],
    ["58a", "5a", "The Masked Magician", "Butch Hartman", "Scott Fellows", "Dave Thomas", "February 18, 2005"],
    ["58b", "5b", "The Big Bash", "Ken Bruce and Juli Hashiguchi", "Cynthia True", "Maureen Mascarina and Shawn Murray", "February 18, 2005"],
    ["59a", "6a", "Blondas Have More Fun!", "Gary Conrad", "Scott Fellows", "Mike Manley", "April 2, 2005"],
    ["59b", "6b", "Five Days of F.L.A.R.G.", "Ken Bruce", "Scott Fellows", "Maureen Mascarina", "April 2, 2005"],
    ["60a", "7a", "Go Young, West Man!", "Sarah Frost", "Jack Thomas", "Aaron Rozenfeld and Butch Hartman", "May 9, 2005"],
    ["60b", "7b", "Birthday Wish!", "Ken Bruce", "Cynthia True", "Brandon Kruse and Shawn Murray", "May 9, 2005"],
    ["61a", "8a", "Timmy's 2-D House of Horror", "Gary Conrad", "Cynthia True", "Heather Martinez", "May 10, 2005"],
    ["61b", "8b", "It's a Wishful Life", "Sarah Frost", "Jack Thomas", "Tom King", "May 10, 2005"],
    ["62a", "9a", "Escape from Unwish Island", "Ken Bruce", "Scott Fellows", "Shawn Murray", "May 11, 2005"],
    ["62b", "9b", "The Gland Plan", "Sarah Frost", "Jack Thomas", "Aaron Rozenfeld", "May 11, 2005"],
    ["63a", "10a", "Hassle in the Castle", "Gary Conrad", "Jack Thomas", "Heather Martinez", "May 12, 2005"],
    ["63b", "10b", "Remy Rides Again", "Sarah Frost", "Jack Thomas", "Tom King", "May 12, 2005"],
    ["64a", "11a", "Talkin' Trash", "Sarah Frost", "Jack Thomas", "Tom King and Maureen Mascarina", "May 13, 2005"],
    ["64b", "11b", "Timmy TV", "Ken Bruce", "Cynthia True", "Shawn Murray", "May 13, 2005"],
    ["65", "12", "School's Out!: The Musical", "Butch Hartman", "Steve Marmel and Butch Hartman", "Dave Thomas, Tom King, Heather Martinez, Maureen Mascarina, Shawn Murray, and Aaron Rozenfeld", "June 10, 2005"],
    ["66a", "13a", "Mooooving Day", "Gary Conrad", "Gene Grillo Story by: Jack Thomas (story)", "Dave Thomas", "October 3, 2005"],
    ["66b", "13b", "Big Wanda", "Ken Bruce", "Jack Thomas", "Butch Hartman", "October 3, 2005"],
    ["67a", "14a", "Oh, Brother!", "Gary Conrad", "Kevin Sullivan Story by: Kevin Sullivan and Deirdre Brenner (story)", "Steve Daye", "October 4, 2005"],
    ["67b", "14b", "What's the Difference?", "Ken Bruce", "Jack Thomas", "Maureen Mascarina", "October 4, 2005"],
    ["68a", "15a", "Smart Attack!", "Ken Bruce", "Greg Fideler", "Dave Thomas", "October 5, 2005"],
    ["68b", "15b", "Operation F.U.N.", "Gary Conrad", "Cynthia True", "Dave Cunningham", "October 5, 2005"],
    ["69a", "16a", "Something's Fishy!", "Gary Conrad", "Steve Marmel and Jack Thomas", "Brandon Kruse", "October 6, 2005"],
    ["69b", "16b", "Presto Change-O", "Ken Bruce", "Kevin Sullivan Story by: Deirdre Brenner and Kevin Sullivan (story)", "Maureen Mascarina", "October 6, 2005"],
    ["70a", "17a", "The Good Old Days!", "Gary Conrad", "Dave Thomas Story by: Dave Thomas and Steve Marmel (story)", "Dave Thomas", "October 7, 2005"],
    ["70b", "17b", "Future Lost", "Ken Bruce", "Jack Thomas", "Dave Cunningham and Butch Hartman", "October 7, 2005"],
    ["71", "18", "The Jimmy Timmy Power Hour 2: When Nerds Collide!", "Keith Alcorn, Mike Gasaway, and Butch Hartman", "Gene Grillo and Steve Marmel Gene Grillo, Steve Marmel, Jed Spingarn, and Jack Thomas (story)", "Jason Dorf, Rod Douglas, Dan Nosella, Maureen Mascarina, Steve Daye & Butch Hartman", "January 16, 2006"],
    ["72", "19", "Fairy Idol", "Ken Bruce and Gary Conrad", "Butch Hartman and Steve Marmel Story by: Steve Marmel, Dave Thomas, and Kevin Sullivan (story)", "Steve Daye, Maureen Mascarina, Dave Thomas, and Butch Hartman", "May 19, 2006"],
    ["73", "20", "The Jimmy Timmy Power Hour 3: The Jerkinators!", "Keith Alcorn, Mike Gasaway, and Butch Hartman", "Steve Marmel and Jed Spingarn", "Jason Dorf, Rod Douglas, Dan Nosella, Dave Cunningham, Steve Daye, Maureen Mascarina, Dave Thomas & Butch Hartman", "July 21, 2006"],
    ["74a", "21a", "Timmy the Barbarian!", "Ken Bruce", "Story by: Dave Thomas (story) Jack Thomas and Steve Marmel", "Dave Thomas", "November 25, 2006"],
    ["74b", "21b", "No Substitute for Crazy!", "Gary Conrad", "Kevin Sullivan", "Dave Cunningham and Butch Hartman", "November 25, 2006"]
];

var season6 = [
    ["75", "1", "Fairly OddBaby", "Ken Bruce, Michelle Bryan, and Gary Conrad", "Scott Fellows, Butch Hartman & Kevin Sullivan", "Wincat Alcala, Aaron Hammersley, Butch Hartman & Marty Warner", "February 18, 2008"],
    ["76a", "2a", "Mission: Responsible", "Michelle Bryan", "Scott Fellows", "Butch Hartman", "March 10, 2008"],
    ["76b", "2b", "Hairicane", "Ken Bruce", "Kevin Sullivan", "Brandon Kruse", "March 11, 2008"],
    ["77a", "3a", "Open Wide and Say Aaagh!", "Gary Conrad", "Butch Hartman", "Wincat Alcala", "March 12, 2008"],
    ["77b", "3b", "Odd Pirates", "Michelle Bryan", "Kevin Sullivan", "Butch Hartman & Marty Warner", "March 13, 2008"],
    ["78a", "4a", "The Odd Squad", "Michelle Bryan", "Scott Fellows", "Brandon Kruse", "May 12, 2008"],
    ["78b", "4b", "For Emergencies Only", "Ken Bruce", "Butch Hartman", "Wincat Alcala", "May 13, 2008"],
    ["79a", "5a", "Cheese & Crockers", "Michelle Bryan", "Scott Fellows", "Butch Hartman", "May 14, 2008"],
    ["79b", "5b", "Land Before Timmy", "Gary Conrad", "Written by: Kevin Sullivan Story by: Tom Krajewski (story)", "Ray Angrum and Butch Hartman", "May 15, 2008"],
    ["80a", "6a", "King Chang", "Michelle Bryan", "Kevin Sullivan", "Wincat Alcala", "May 16, 2008"],
    ["80b", "6b", "The End of the Universe-ity", "Ken Bruce", "Scott Fellows", "Butch Hartman and Ray Angrum", "August 11, 2008"],
    ["81", "7", "The Fairly Oddlymipics", "Ken Bruce and Gary Conrad", "Scott Fellows, Butch Hartman, and Kevin Sullivan", "Aaron Hammersley and Butch Hartman", "August 1, 2008"],
    ["82a", "8a", "Sooper Poof", "Gary Conrad", "Laurie Israel and Rachel Ruderman", "Aaron Hammersley", "August 12, 2008"],
    ["82b", "8b", "Wishing Well", "Michelle Bryan", "Kevin Sullivan", "Butch Hartman", "August 13, 2008"],
    ["83a", "9a", "Wishy Washy", "Ken Bruce", "Butch Hartman", "Brandon Kruse", "August 14, 2008"],
    ["83b", "9b", "Poof's Playdate", "Gary Conrad", "Scott Fellows", "Butch Hartman", "August 15, 2008"],
    ["84a", "10a", "Vicky Gets Fired", "Ken Bruce", "Kevin Sullivan", "Aaron Hammersley", "November 30, 2008"],
    ["84b", "10b", "Chindred Spirits", "Michelle Bryan", "Amy Keating Rogers", "Butch Hartman and Ray Angrum", "November 30, 2008"],
    ["85a", "11a", "9 Lives!", "Ken Bruce", "Chris Prouty", "Wincat Alcala", "November 30, 2008"],
    ["85b", "11b", "Dread 'n' Breakfast", "Gary Conrad", "Scott Fellows", "Butch Hartman", "November 30, 2008"],
    ["86", "12", "Merry Wishmas", "Ken Bruce", "Butch Hartman, Scott Fellows, and Kevin Sullivan", "Aaron Hammersley, Butch Hartman, and Brandon Kruse", "December 12, 2008"]
];

var season7 = [
    ["87", "1", "Wishology! Part 1: The Big Beginning", "Butch Hartman", "Scott Fellows, Butch Hartman, and Kevin Sullivan", "Wincat Alcala, Aaron Hammersley, Butch Hartman, and Brandon Kruse", "May 1, 2009", "4.012[3][4]"],
    ["88", "2", "Wishology! Part 2: The Exciting Middle Part", "Butch Hartman", "Scott Fellows, Butch Hartman, and Kevin Sullivan", "Wincat Alcala, Aaron Hammersley, Butch Hartman, and Brandon Kruse", "May 2, 2009", "3.6[3][4]"],
    ["89", "3", "Wishology! Part 3: The Final Ending", "Butch Hartman", "Scott Fellows, Butch Hartman, and Kevin Sullivan", "Aaron Hammersley, Butch Hartman, and Brandon Kruse", "May 3, 2009", "4.071[3][4]"],
    ["90a", "4a", "Bad Heir Day", "Ken Bruce", "Kevin Sullivan", "Aaron Hammersley", "July 6, 2009", "N/A"],
    ["90b", "4b", "Freaks & Greeks", "Gary Conrad", "Tom Krajewski", "Fred Gonzales", "September 30, 2009", "N/A"],
    ["91a", "5a", "Micecapades", "Gary Conrad", "Ray DeLaurentis", "Butch Hartman and Vic Harrisson", "July 8, 2009", "N/A"],
    ["91b", "5b", "Formula for Disaster", "Michelle Bryan", "Will Schifrin", "Butch Hartman and Dan Haskett", "July 7, 2009", "N/A"],
    ["92a", "6a", "Birthday Bashed!", "Michelle Bryan", "Butch Hartman", "Brandon Kruse", "July 9, 2009", "N/A"],
    ["92b", "6b", "Momnipresent", "Gary Conrad", "Kevin Sullivan", "Ray Angrum (as Rayfield Angrum) and Butch Hartman", "August 12, 2009", "N/A"],
    ["93", "7", "Anti-Poof", "Michelle Bryan and Gary Conrad", "Ray DeLaurentis, Butch Hartman, Kevin Sullivan, and Ed Valentine", "Brandon Kruse and Aaron Hammersley", "July 10, 2009", "N/A"],
    ["94a", "8a", "Add-a-Dad", "Michelle Bryan", "Kevin Sullivan", "Heather Martinez", "August 13, 2009", "N/A"],
    ["94b", "8b", "Squirrely Puffs", "Michelle Bryan", "Kevin Sullivan Ray DeLaurentis and Butch Hartman (story)", "Fred Gonzales", "August 11, 2009", "N/A"],
    ["95a", "9a", "Fly Boy", "Michelle Bryan", "Ed Valentine", "Brandon Kruse", "August 14, 2009", "N/A"],
    ["95b", "9b", "Temporary Fairy", "Ken Bruce", "Amy Keating Rogers", "Dave Thomas", "September 29, 2009", "N/A"],
    ["96a", "10a", "Crocker Shocker", "Gary Conrad", "Kevin Sullivan, and Amy Keating Rogers (story)", "Aaron Hammersley", "September 28, 2009", "N/A"],
    ["96b", "10b", "Super Zero", "Ken Bruce", "Ray DeLaurentis and Will Schifrin", "Fred Gonzales", "October 1, 2009", "N/A"],
    ["97a", "11a", "Dadbra-Cadabra", "Gary Conrad", "Gary Conrad", "Dave Thomas", "October 2, 2009", "N/A"],
    ["97b", "11b", "Timmy Turnip", "Michelle Bryan", "Will Schifrin Ray DeLaurentis and Will Schifrin (story)", "Butch Hartman and Cindy Morrow", "August 10, 2009", "N/A"],
    ["98a", "12a", "One Man Banned", "Michelle Bryan", "Ed Valentine", "Aaron Hammersley", "August 16, 2009", "N/A"],
    ["98b", "12b", "Frenemy Mine", "Ken Bruce", "Kevin Sullivan", "Brandon Kruse", "August 16, 2009", "N/A"],
    ["99a", "13a", "Double-Oh Schnozmo!", "Gary Conrad", "Kevin Sullivan", "Brandon Kruse", "September 11, 2010", "N/A"],
    ["99b", "13b", "Planet Poof", "Michelle Bryan", "Ed Valentine", "Dave Thomas", "April 5, 2010", "N/A"],
    ["100a", "14a", "The Boss of Me", "Ken Bruce", "Charlotte Fullerton", "Aaron Hammersley", "September 11, 2010", "N/A"],
    ["100b", "14b", "He Poofs He Scores!", "Michelle Bryan", "Ray DeLaurentis and Will Schifrin", "Fred Gonzales", "April 6, 2010", "N/A"],
    ["101a", "15a", "Playdate of Doom", "Gary Conrad", "Kevin Sullivan", "Heather Martinez", "April 7, 2010", "N/A"],
    ["101b", "15b", "Teacher's Pet", "Ken Bruce", "Ray DeLaurentis and Will Schifrin", "Dave Thomas", "April 8, 2010", "N/A"],
    ["102a", "16a", "Take and Fake", "Ken Bruce", "Kevin Sullivan", "Heather Martinez", "February 6, 2010", "N/A"],
    ["102b", "16b", "Cosmo Rules", "Michelle Bryan", "Joanna Lewis", "Brandon Kruse", "July 11, 2011", "N/A"],
    ["103a", "17a", "Chicken Poofs", "Gary Conrad", "Ray DeLaurentis and Will Schifrin", "Fred Gonzales", "April 9, 2010", "N/A"],
    ["103b", "17b", "Stupid Cupid", "Ken Bruce", "Will Schifrin", "Heather Martinez", "February 6, 2010", "N/A"],
    ["104a", "18a", "Manic Mom-Day", "Michelle Bryan", "Kevin Sullivan", "Brandon Kruse", "September 18, 2010", "N/A"],
    ["104b", "18b", "Crocker of Gold", "Gary Conrad", "Will Schifrin", "Butch Hartman", "September 18, 2010", "N/A"]
];

var season8 = [
    ["105", "1", "Love Triangle", "Ken Bruce and Gary Conrad", "Dave Thomas, Kevin Sullivan, Will Schifrin, Butch Hartman, and Ray DeLaurentis", "Dave Thomas and Fred Gonzales", "February 12, 2011"],
    ["106a", "2a", "Operation: Dinkleberg", "Ken Bruce", "Ray DeLaurentis and Will Schifrin", "Brandon Kruse", "February 26, 2011"],
    ["106b", "2b", "Spellementary School", "Michelle Bryan", "Kevin Sullivan", "Dave Thomas", "February 26, 2011"],
    ["107", "3", "Invasion of the Dads", "Ken Bruce and Michelle Bryan", "Ray DeLaurentis, Will Schifrin, and Kevin Sullivan", "Aaron Hammersley and Butch Hartman", "June 18, 2011"],
    ["108a", "4a", "Farm Pit", "Michelle Bryan", "Ed Valentine", "Fred Gonzales", "August 5, 2012"],
    ["108b", "4b", "Crock Talk", "Gary Conrad", "Ray DeLaurentis and Will Schifrin", "Heather Martinez and Butch Hartman", "July 11, 2011"],
    ["109a", "5a", "Food Fight", "Michelle Bryan", "Ed Valentine", "Aaron Hammersley", "July 12, 2011"],
    ["109b", "5b", "Please Don't Feed the Turners", "Gary Conrad", "Ray DeLaurentis and Will Schifrin", "Fred Gonzales", "July 12, 2011"],
    ["110a", "6a", "Lights Out", "Ken Bruce", "Kevin Sullivan", "Dave Thomas", "July 13, 2011"],
    ["110b", "6b", "Dad Overboard", "Gary Conrad", "Ray DeLaurentis and Will Schifrin", "Aaron Hammersley", "July 13, 2011"],
    ["111a", "7a", "Old Man and the C-", "Gary Conrad", "Kevin Sullivan", "Dave Thomas", "July 14, 2011"],
    ["111b", "7b", "Balance of Flour", "Ken Bruce", "Ray DeLaurentis and Will Schifrin", "Brandon Kruse", "July 14, 2011"],
    ["112a", "8a", "Beach Blanket Bozos", "Michelle Bryan", "Ed Valentine", "Heather Martinez", "August 15, 2011"],
    ["112b", "8b", "Poltergeeks", "Ken Bruce", "Ed Valentine", "Fred Gonzales and Greg Rankin", "August 15, 2011"],
    ["113", "9", "When L.O.S.E.R.S. Attack", "John McIntyre and Ken Bruce", "Ray DeLaurentis, Will Schifrin, and Kevin Sullivan", "Ed Baker and Butch Hartman", "October 15, 2011"],
    ["114", "10", "Timmy's Secret Wish!", "Michelle Bryan, Ken Bruce, and John McIntyre", "Will Schifrin and Kevin Sullivan", "Dave Thomas", "November 23, 2011"],
    ["115", "11", "Meet the OddParents", "Michelle Bryan and John McIntyre", "Ray DeLaurentis, Will Schifrin, and Kevin Sullivan", "Aaron Hammersley, Butch Hartman, and Dave Thomas", "December 29, 2011"]
];
var season9 = [
    ["116", "1", "Fairly OddPet", "Gary Conrad and Tuck Tucker", "Ray DeLaurentis, Will Schifrin, and Kevin Sullivan", "Miguel Puga and Josh Zinman", "March 23, 2013", "3.90[5]"],
    ["117a", "2a", "Dinklescouts", "Gary Conrad", "Kevin Arrieta and Sindy Spackman", "Marcelo DeSouza", "April 14, 2013", "2.06[6]"],
    ["117b", "2b", "I Dream of Cosmo", "Randy Myers and Michelle Bryan", "Kevin Arrieta and Sindy Spackman", "Mike Nassar and Butch Hartman", "April 14, 2013", "2.06[6]"],
    ["118a", "3a", "Turner & Pooch", "Tuck Tucker", "Ray DeLaurentis, Will Schifrin, and Kevin Sullivan", "Butch Hartman and Jim Mortensen", "May 4, 2013", "3.10[7]"],
    ["118b", "3b", "Dumbbell Curve", "Randy Myers and Michelle Bryan", "Kevin Arrieta, Ray DeLaurentis, Will Schifrin, Sindy Spackman, and Kevin Sullivan", "Josh Zinman and Butch Hartman", "May 11, 2013", "3.05[8]"],
    ["119a", "4a", "The Terrible Twosome", "Gary Conrad", "Ray DeLaurentis, Will Schifrin, and Kevin Sullivan", "Miguel Puga", "June 1, 2013", "3.19[9]"],
    ["119b", "4b", "App Trap", "Tuck Tucker and Butch Hartman", "Alec Schwimmer (story) Kevin Arrieta and Sindy Spackman", "Mike Nassar and Butch Hartman", "June 8, 2013", "2.73[10]"],
    ["120a", "5a", "Force of Nature", "Michelle Bryan and Randy Myers", "Kevin Arrieta and Sindy Spackman", "Marcelo DeSouza", "June 15, 2013", "3.03[11]"],
    ["120b", "5b", "Viral Vidiots", "Gary Conrad", "Ellen Byron and Lissa Kapstrom", "Jim Mortensen and Butch Hartman", "June 22, 2013", "3.22[12]"],
    ["121", "6", "Scary GodCouple", "Michelle Bryan, Butch Hartman, Randy Myers, and Tuck Tucker", "Ray DeLaurentis, Will Schifrin, and Kevin Sullivan", "Miguel Puga, Josh Zinman, and Butch Hartman", "October 19, 2013", "3.00[13]"],
    ["122a", "7a", "Finding Emo", "Michelle Bryan and Randy Myers", "Ray DeLaurentis, Will Schifrin, and Kevin Sullivan", "Jim Mortensen and Butch Hartman", "July 9, 2014", "N/A"],
    ["122b", "7b", "Dust Busters", "Michelle Byran, Kevin Petrilak, and Tuck Tucker", "Jonathan Butler, Ray DeLaurentis, Will Schifrin, and Kevin Sullivan", "Marcelo DeSouza", "July 9, 2014", "N/A"],
    ["123a", "8a", "The Bored Identity", "Michelle Bryan, Kevin Petrilak, and Tuck Tucker", "Ray DeLaurentis, Will Schifrin, and Kevin Sullivan", "Miguel Puga", "July 23, 2014", "1.80[14]"],
    ["123b", "8b", "Country Clubbed", "Michelle Bryan", "Kevin Arrieta, Alec Schwimmer, and Sindy Spackman", "Mike Nassar and Butch Hartman", "July 23, 2014", "1.80[14]"],
    ["124a", "9a", "Dog Gone", "Gary Conrad", "Kevin Arrieta, Ray DeLaurentis, Will Schifrin, Sindy Spackman, and Kevin Sullivan", "Marcelo DeSouza", "July 28, 2014", "1.80[15]"],
    ["124b", "9b", "Turner Back Time", "Michelle Bryan, Kevin Petrilak, and Tuck Tucker", "Ellen Byron and Lissa Kapstrom", "Jim Mortensen and Butch Hartman", "July 28, 2014", "1.80[15]"],
    ["125a", "10a", "Cosmonopoly", "Michelle Bryan", "Ray DeLaurentis, Will Schifrin, Kevin Sullivan, and Becky Wangberg", "Mike Milo and Butch Hartman", "July 7, 2014", "N/A"],
    ["125b", "10b", "Hero Hound", "Gary Conrad", "Kevin Arrieta", "Miguel Puga", "July 7, 2014", "N/A"],
    ["126a", "11a", "A Boy and His Dog-Boy", "Michelle Bryan", "Sindy Spackman", "Marcelo DeSouza", "July 8, 2014", "N/A"],
    ["126b", "11b", "Crock Blocked", "Michelle Bryan, Kevin Petrilak, and Tuck Tucker", "Sindy Spackman", "Mike Nassar and Butch Hartman", "July 8, 2014", "N/A"],
    ["127", "12", "School of Crock", "Ken Bruce and Michelle Bryan", "Ray DeLaurentis, Will Schifrin, Alec Schwimmer, and Kevin Sullivan", "Wolf-Rüdiger Bloss and Fred Gonzales", "May 26, 2014", "2.45[16]"],
    ["128", "13", "The Past and the Furious", "Michelle Bryan and Gary Conrad", "Ray DeLaurentis, Will Schifrin, Alec Schwimmer, and Kevin Sullivan", "Wolf-Rüdiger Bloss, Marcelo DeSouza, and Brandon Kruse", "July 11, 2014", "N/A"],
    ["129a", "14a", "Let Sleeper Dogs Lie", "Michelle Bryan", "Sindy Spackman", "Miguel Puga", "July 14, 2014", "1.86[17]"],
    ["129b", "14b", "Cat-Astrophe", "Gary Conrad", "Alec Schwimmer", "Mike Nassar and Butch Hartman", "July 14, 2014", "1.86[17]"],
    ["130a", "15a", "Jerk of All Trades", "Michelle Bryan", "Sindy Spackman", "Mike Nassar and Butch Hartman", "July 15, 2014", "1.85[18]"],
    ["130b", "15b", "Snack Attack", "Gary Conrad", "Alec Schwimmer (story) Ray DeLaurentis, Will Schifrin, and Kevin Sullivan", "Marcelo DeSouza", "July 15, 2014", "1.85[18]"],
    ["131a", "16a", "Turning Into Turner", "Kevin Petrilak", "Joanna Lewis, Alec Schwimmer, and Kristine Songco", "Jim Mortensen and Butch Hartman", "July 16, 2014", "1.91[19]"],
    ["131b", "16b", "The Wand That Got Away", "Michelle Bryan", "Sindy Spackman", "Mike Milo and Butch Hartman", "July 16, 2014", "1.91[19]"],
    ["132", "17", "Dimmsdale Tales", "Ken Bruce and Gary Conrad", "Joanna Lewis, Alec Schwimmer, Kristine Songco, and Sindy Spackman", "Brandon Kruse and Miguel Puga", "July 18, 2014", "N/A"],
    ["133a", "18a", "Love at First Bark", "Gary Conrad", "Ray DeLaurentis, Will Schifrin, and Kevin Sullivan", "Mike Milo and Butch Hartman", "July 21, 2014", "N/A"],
    ["133b", "18b", "Desperate Without Housewives", "Kevin Petrilak", "Lissa Kapstrom", "Miguel Puga", "July 21, 2014", "N/A"],
    ["134a", "19a", "Stage Fright", "Gary Conrad", "Joanna Lewis, Kristine Songco, and Becky Wangberg", "Miguel Puga", "July 22, 2014", "N/A"],
    ["134b", "19b", "Gone Flushin'", "Kevin Petrilak", "Lissa Kapstrom", "Mike Nassar and Butch Hartman", "July 22, 2014", "N/A"],
    ["135a", "20a", "Two and a Half Babies", "Gary Conrad", "Sindy Spackman", "Mike Milo and Butch Hartman", "July 25, 2014[N 1]", "1.57[20]"],
    ["135b", "20b", "Anchor's Away", "Gary Conrad", "Kevin Arrieta and Sindy Spackman", "Mike Nassar and Butch Hartman", "July 25, 2014[N 1]", "1.57[20]"],
    ["136a", "21a", "Weirdos on a Train", "Gary Conrad", "Ray DeLaurentis, Kevin Sullivan, and Will Schifrin", "Jim Mortensen and Butch Hartman", "July 29, 2014", "N/A"],
    ["136b", "21b", "Tons of Timmys", "Michelle Bryan, Kevin Petrilak, and Tuck Tucker", "Lissa Kapstrom", "Mike Milo and Butch Hartman", "July 29, 2014", "N/A"],
    ["137a", "22a", "Lame Ducks", "Michelle Bryan", "Sindy Spackman", "Jim Mortensen and Butch Hartman", "July 30, 2014", "2.21[21]"],
    ["137b", "22b", "A Perfect Nightmare", "Kevin Petrilak", "Ray DeLaurentis, Will Schifrin, and Kevin Sullivan", "Marcelo DeSouza", "July 30, 2014", "2.12[21]"],
    ["138", "23", "Fairly Odd Fairy Tales", "Ken Bruce and Gary Conrad", "Whitney Fox, Joanna Lewis, Alec Schwimmer, and Kristine Songco", "Marcelo DeSouza and Brandon Kruse", "August 1, 2014", "2.14[22]"],
    ["139", "24", "Man's Worst Friend", "Michelle Bryan and Gary Conrad", "Ray DeLaurentis, Will Schifrin, Alec Schwimmer, and Kevin Sullivan", "Wolf-Rüdiger Bloss and Fred Gonzales", "February 8, 2015[N 2]", "1.48[23]"],
    ["140", "25", "Fairly Old Parent", "Michelle Bryan and Gary Conrad", "Ray DeLaurentis, Will Schifrin, Alec Schwimmer, Kevin Sullivan, and Becky Wangberg", "Marcelo DeSouza, Jim Mortensen, and Butch Hartman", "March 28, 2015[N 3]", "1.95[24]"],
    ["141", "26", "The Fairy Beginning", "Ken Bruce and Michelle Bryan", "Ray DeLaurentis, Will Schifrin, Alec Schwimmer, and Kevin Sullivan", "Fred Gonzales, Brandon Kruse, and Miguel Puga", "March 28, 2015[N 4]", "2.03[24]"]
];
var season10 = [
    ["142", "1", "The Big Fairy Share Scare!", "Ken Bruce and John McIntyre", "Ellen Byron, Ray DeLaurentis, and Lissa Kapstrom", "Fred Gonzales and Butch Hartman", "January 15, 2016", "1.20[25]"],
    ["143a", "2a", "Whittle Me This!", "John McIntyre", "Ellen Byron, Bob Colleary, Ray DeLaurentis, and Lissa Kapstrom", "Sarah Johnson", "January 22, 2016", "1.23[26]"],
    ["143b", "2b", "Mayor May Not", "Ken Bruce", "Ellen Byron, Bob Colleary, Ray DeLaurentis, and Lissa Kapstrom", "Butch Hartman and Paul Lee", "January 29, 2016", "1.13[27]"],
    ["144a", "3a", "Girly Squirrely", "Sherie Pollack", "Ellen Byron, Bob Colleary, Ray DeLaurentis, and Lissa Kapstrom", "John West", "February 5, 2016", "1.30[28]"],
    ["144b", "3b", "Birthday Battle", "Sherie Pollack", "Ellen Byron, Bob Colleary, Ray DeLaurentis, and Lissa Kapstrom", "Gavin Freitas", "February 19, 2016", "1.22[29]"],
    ["145a", "4a", "The Fair Bears", "John McIntyre", "Ellen Byron, Bob Colleary, Ray DeLaurentis, and Lissa Kapstrom", "Benji Williams", "February 26, 2016", "1.27[30]"],
    ["145b", "4b", "Return of the L.O.S.E.R.S.", "Ken Bruce", "Ellen Byron, Bob Colleary, Ray DeLaurentis, and Lissa Kapstrom", "Gavin Freitas", "June 14, 2017[N 5]", "0.17[31]"],
    ["146a", "5a", "A Sash and a Rash", "Sherie Pollack", "Ellen Byron, Bob Colleary, Ray DeLaurentis, and Lissa Kapstrom", "Sarah Johnson", "September 12, 2016[N 6]", "1.46[32]"],
    ["146b", "5b", "Fish Out of Water", "John McIntyre", "Ellen Byron, Bob Colleary, Ray DeLaurentis, and Lissa Kapstrom", "Butch Hartman and Paul Lee", "September 12, 2016[N 6]", "1.46[32]"],
    ["147a", "6a", "Animal Crockers", "Ken Bruce", "Ellen Byron, Ray DeLaurentis, Bob Colleary, and Lissa Kapstrom", "Sarah Johnson", "September 14, 2016[N 7]", "1.36[33]"],
    ["147b", "6b", "One Flu Over the Crocker's Nest", "Ken Bruce", "Ellen Byron, Bob Colleary, Ray DeLaurentis, and Lissa Kapstrom", "John West", "September 14, 2016[N 7]", "1.36[33]"],
    ["148", "7", "Booby Trapped", "John McIntyre and Sherie Pollack", "Ellen Byron, Bob Colleary, Ray DeLaurentis, and Lissa Kapstrom", "Gavin Freitas, Sarah Johnson, and Benji Williams", "September 16, 2016[N 8]", "1.60[34]"],
    ["149a", "8a", "Blue Angel", "John McIntyre", "Bob Colleary and Ray DeLaurentis", "John West", "September 13, 2016[N 9]", "1.39[35]"],
    ["149b", "8b", "Marked Man", "Sherie Pollack", "Ellen Byron, Bob Colleary, Ray DeLaurentis, Lissa Kapstrom, and Becky Wangberg", "Butch Hartman and Paul Lee", "September 13, 2016[N 9]", "1.39[36]"],
    ["150a", "9a", "Clark Laser", "Ken Bruce", "Ray DeLaurentis", "Benji Williams", "September 15, 2016[N 10]", "1.55[37]"],
    ["150b", "9b", "Married to the Mom", "Sherie Pollack", "Ellen Byron and Lissa Kapstrom", "Gavin Freitas", "September 15, 2016[N 10]", "1.55[38]"],
    ["151a", "10a", "Which Is Wish", "John McIntyre", "Ellen Byron, Bob Colleary, Ray DeLaurentis, and Lissa Kapstrom", "Sarah Johnson", "June 21, 2017[N 11]", "0.22[39]"],
    ["151b", "10b", "Nuts and Dangerous", "Ken Bruce", "Bob Colleary, Ray DeLaurentis, and Lissa Kapstrom", "Butch Hartman and Paul Lee", "February 22, 2017[N 11]", "N/A"],
    ["152a", "11a", "Fairy Con", "John McIntyre", "Ellen Byron, Bob Colleary, and Ray DeLaurentis", "Benji Williams", "June 28, 2017[N 12]", "0.23[40]"],
    ["152b", "11b", "The Hungry Games", "Sherie Pollack", "Becky Wangberg", "John West", "July 12, 2017[N 13]", "0.26[41]"],
    ["153a", "12a", "Spring Break-Up", "Ken Bruce", "Ellen Byron, Bob Colleary, Ray DeLaurentis and Lissa Kapstrom", "Gavin Freitas", "February 1, 2017[N 14]", "0.21[42]"],
    ["153b", "12b", "Dimmsdale Daze", "Sherie Pollack", "Ellen Byron, Bob Colleary, Ray DeLaurentis and Lissa Kapstrom", "Sarah Johnson", "June 21, 2017[N 15]", "0.22[43]"],
    ["154a", "13a", "Cat 'n Mouse", "Ken Bruce", "Ellen Byron, Bob Colleary, Ray DeLaurentis, and Lissa Kapstrom", "Sarah Johnson and Paul Lee", "February 22, 2017[N 16]", "N/A"],
    ["154b", "13b", "Chip Off the Old Crock!", "Sherie Pollack", "Ellen Byron, Bob Colleary, Ray DeLaurentis and Lissa Kapstrom", "John West", "June 28, 2017[N 17]", "0.23[44]"],
    ["155a", "14a", "Space Ca-Dad", "George Elliott and Keith Oliver", "Ellen Byron, Bob Colleary, Ray DeLaurentis and Lissa Kapstrom", "Steve Daye", "July 19, 2017[N 18]", "0.28[45]"],
    ["155b", "14b", "Summer Bummer", "George Elliott and Keith Oliver", "Ellen Byron, Bob Colleary, Ray DeLaurentis and Lissa Kapstrom", "Ted Collyer", "July 12, 2017[N 19]", "0.26[46]"],
    ["156a", "15a", "Hare Raiser", "George Elliott and Keith Oliver", "Ellen Byron, Bob Colleary, Ray DeLaurentis and Lissa Kapstrom", "Blayne Burnside and Brian Coughlan", "July 26, 2017[N 20]", "0.38[47]"],
    ["156b", "15b", "The Kale Patch Caper", "George Elliott and Keith Oliver", "Ellen Byron, Bob Colleary, Ray DeLaurentis, Lissa Kapstrom, and Becky Wangberg", "Steve Daye", "July 26, 2017[N 21]", "0.38[48]"],
    ["157a", "16a", "Dadlantis", "George Elliott and Keith Oliver", "Ellen Byron, Bob Colleary, Ray DeLaurentis and Lissa Kapstrom", "Blayne Burnside, Brian Wong, and Gerry Duchemin", "February 8, 2017[N 22]", "N/A"],
    ["157b", "16b", "Chloe Rules!", "George Elliott and Keith Oliver", "Ellen Byron, Bob Colleary, Ray DeLaurentis and Lissa Kapstrom", "Steve Remen", "February 15, 2017[N 23]", "0.14[49]"],
    ["158a", "17a", "Crockin' the House", "George Elliott and Keith Oliver", "Ellen Byron, Bob Colleary, Ray DeLaurentis and Lissa Kapstrom", "Ted Collyer", "January 25, 2017[N 24]", "0.17[50]"],
    ["158b", "17b", "Tardy Sauce", "George Elliott and Keith Oliver", "Ellen Byron, Bob Colleary, Ray DeLaurentis and Lissa Kapstrom", "Brian Coughlan", "February 15, 2017[N 25]", "0.14[49]"],
    ["159a", "18a", "Knitwits", "George Elliott and Keith Oliver", "Ellen Byron, Bob Colleary, Ray DeLaurentis and Lissa Kapstrom", "Gerry Duchemin", "February 8, 2017", "N/A"],
    ["159b", "18b", "Dimmsdale's Got Talent?", "George Elliott and Keith Oliver", "Ellen Byron, Bob Colleary, Ray DeLaurentis, Lissa Kapstrom, and Becky Wangberg", "Steve Daye and Seema Virdi", "June 14, 2017", "0.17[51]"],
    ["160", "19", "Certifiable Super Sitter", "George Elliott and Keith Oliver", "Ellen Byron, Bob Colleary, Ray DeLaurentis and Lissa Kapstrom Kiley Vorndran (story)", "Simon Paquette and Ted Collyer", "January 18, 2017", "0.23[52]"],
    ["161a", "20a", "Goldie-Crocks and the Three Fair Bears", "George Elliott and Keith Oliver", "Ray DeLaurentis and Will Schifrin", "Katie Shanahan", "July 19, 2017[N 26]", "0.28[53]"],
    ["161b", "20b", "Fancy Schmancy", "George Elliott and Keith Oliver", "Becky Wangberg", "Brian Coughlan", "February 1, 2017", "0.21[42]"]
];

var seasons = [...season1, ...season2, ...season3, ...season4, ...season5, ...season6, ...season7, ...season8, ...season9, ...season10];
console.log(seasons);
var seasonData = [];
seasons.forEach(season => {
    seasonData.push({
        "No. overall": season[0],
        "No. in season": season[1],
        "Title": season[2],
        "Directed by": season[3],
        "Written by": season[4],
        "Storyboard by": season[5],
        "Original air date": season[6],
        "Viewers (millions)": season[7]
    });
});
seasonData = JSON.stringify(seasonData);
// copy(seasonData);